### ISSUE TITLE
About the file of Rafd_image.csv

### ISSUE THREAD

**Issue by Jessicall** [yingcong/HomoInterpGAN#12]
Hi～   @yingcong Could you share the file of Rafd_image.csv or give me some suggestion about creating it?I'm confused of it.Thank you.

**Comment by yingcong** [comment]
Hi @Jessicall  It is attached. 
[rafd.zip](https://github.com/yingcong/HomoInterpGAN/files/3895958/rafd.zip)

**Comment by Jessicall** [comment]
Hi@yingcong Thanks for your reply .But I still encountered too many errors during testing and got bad results.Could you provide the code of this work training on RaFD dataset.I'm a newbie and just want to learn from it.Thanks very much.Looking forward  to your reply.
