### ISSUE TITLE
Questions about the results in supplementary material

### ISSUE THREAD

**Issue by RegisWu** [yingcong/HomoInterpGAN#4]
Thanks for sharing the nice work!

I have a few questions about the results of testing RaFD model on wild images:
1. As the images in RaFD dataset are well aligned, I am wondering whether you take any alignment steps there? Or just simply crop the face -> transform the expression -> place it back to the original image?
2. May I know whether you use all the images in RaFD to train the model or only the images under frontal camera (90 degree)?

Looking forward to your reply. Thanks.

**Comment by yingcong** [comment]
Thanks for being interested in this work.

1. Yes, the RaFD datasets are well aligned to the CelebA. The alignment tool will crop the head based on the head location of the reference image.

2. Only frontal faces are used.

**Comment by RegisWu** [comment]
@yingcong Thanks for your quick reply!

I try the provided facealign/align_all.py, which it aligns the face to a near-frontal position and good synthesized results could be obtained from that.
But I am still wondering how to put the synthesized face back to the original image, as we have to deal with the scaling/ translation/ rotation problems? I am stuck there.
Could you please share the tool with us? Then we could test the method in a better way. Or could you give us some suggestions on addressing the problem?

Looking forward to your reply. Thanks.

**Comment by RegisWu** [comment]
We would like to generate similar results as Fig.1 - 3 shown in supplementary material

**Comment by yingcong** [comment]
Hi @RegisWu, For blending the faces back, we basically leverage the "seamlessClone“ in opencv. You can refer to https://www.learnopencv.com/seamless-cloning-using-opencv-python-cpp for the usage.

**Comment by RegisWu** [comment]
Note with thanks!
