### ISSUE TITLE
How to train this code on RafD dataset? Could you also share the pretrained model on RaFD? Thanks

### ISSUE THREAD

**Issue by ZhiwenShao** [yingcong/HomoInterpGAN#6]

**Comment by yingcong** [comment]
OK, it will be released later. Actually there is nothing special with the RaFD dataset. We align RaFD dataset with CelebA dataset with the provided tool, and use only frontal faces for training and testing.

**Comment by ZhiwenShao** [comment]
Glad to hear from you. Thank you!

**Comment by yingcong** [comment]
The pretrained model for RaFD can be found here:
https://www.dropbox.com/sh/318th1ahf411pkp/AABpXS64ieHxy-OkPGYtG8Q0a?dl=0
The 37 and 43 identities are used for test and other frontal faces are used for training. 

The interpolator contains 4 branches, and the meaning of the first 3 branches can be found in Table 2 of the original paper.

**Comment by ZhiwenShao** [comment]
Thanks very much for your kind help! I will test the model.
