### ISSUE TITLE
Why we need "Rigorous Training" for attribute classifier ?

### ISSUE THREAD

**Issue by LeoXing1996** [yingcong/HomoInterpGAN#8]
First of all, congratulation for this outstanding work, but I still have two small questions:

* Why we need "Rigorous Training" for attribute classifier ? Can you give a more exactly example? 
* Can I consider T^k in interpolator as a "fliter" used to get rid of variables which are not related to correspond attribute from "feature code" F ?

Thanks!

**Comment by yingcong** [comment]
From my observation, without the rigorous training, the homomorphic loss does not take effect. 
The results is shown in Fig. 3(d) 
If you want to reproduce this phenomenon, you could  try to replace 
https://github.com/yingcong/HomoInterpGAN/blob/b32f4af3100a8946bc5a31f3ee679181a1726848/optimizer/optim_homoInterp.py#L159
with 
        self.loss['discrim_cls'] = classification_loss_list(real_attr, att_detach)


Can I consider T^k in interpolator as a "fliter" used to get rid of variables which are not related to correspond attribute from "feature code" F ?

Yes, you can view it like this.

**Comment by LeoXing1996** [comment]
I get this. Thanks a lot.
