### ISSUE TITLE
Interpolation between dogs and cats

### ISSUE THREAD

**Issue by ligaozhe** [yingcong/HomoInterpGAN#9]
Hello! I am very interested in your work, especially the interpolation between dogs and cats. I saw this result at supplementary material. I want to interpolate without attribute, because there is no label or attribute in my dataset. So could you please tell me how to do?

**Comment by yingcong** [comment]
Hi ligaozhe, in our implementation, we create labels "is_cat" and "is_dog", so that the method can work like celeba or rafd.

**Comment by ligaozhe** [comment]
Thanks for your reply! But I still don't understand how to produce the intermediate result. If I only set two label, is_cat and is_dog, does the selective vector in interp_net only contain two items? Does the model only produce 2 result in this case? For example, If I want to produce 5 intermediate result like you did in paper, how should I do? Thank you so much.
![图片](https://user-images.githubusercontent.com/32236177/67873191-09bf0a00-fb6e-11e9-970a-b5e8fa9b7bf8.png)

**Comment by yingcong** [comment]
Although the labels are binary, with the Homomorphic loss, we have modeled the intermediate regions between cat and dog domains. So during testing, we can simply use floating-point labels to generate intermediate results. 

Note that RaFD and CelebA are similar, i.e., both of them have binary labels, but we can synthesize intermediate results.

**Comment by ligaozhe** [comment]
OK, I will try it. Thanks for your answer!

**Comment by ligaozhe** [comment]
I have run the code. But I am still confused. What is the "floating-point labels"? Could you please describe it in the code? If I use only 2 attributes, I found selective_vector only contains 3 items in the function 'test_selected_curve', so which variable should I modify if I want to generate imterdediate results more than 3?

**Comment by ligaozhe** [comment]
OK，I got it. And I have reproduced your results in cat2dog dataset. Thanks for your work!

**Comment by HelenMao** [comment]
Hi, I want to reimplement the cat2dog continuous translation results too.
Have you reproduced that? Could you share some experience with that?
@ligaozhe  
Thanks!
